version: '3.1'
services:
    web:
        build: .
        ports: 
            - 3000:3000
        depends_on: 
            - postgres 
    postgres:
        image: postgres
        enviroment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secretpassword
        ports: 
            - 5432:5432
        volumes:
            - inlamningBN-db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        ports: 
            - 5050:5050
volumes:
    inlamningBN-d:
